### ISSUE TITLE
Sam - Week 8 Crossover Grading

### ISSUE THREAD

**Issue by dsblack0** [dsblack0/runtime-terror#77]
### FRQs
[Full FRQ Runtime](https://www.dnclubsearch.tech/samAbout)
[Individual Journal Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal) with FRQ details & code links
[Review Video](https://drive.google.com/file/d/1FamcbzbxLSOLJK0NhwdQdRrDKEiAqujB/view?usp=sharing)

| FRQ # | Completed | Deployed |  Documentation | Input? |
| ---      | ---               | ---            | ---                       | ---       |
| 2 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 3 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 4 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 5 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 6 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 7 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 8 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |
| 9 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [ ] </li></ul> |
| 10 |  <ul><li>- [x] </li></ul> | [AboutMe Page](https://www.dnclubsearch.tech/samAbout) | [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Sam-Individual-Journal#frq-details) | <ul><li>- [x] </li></ul> |

### Reflection
- The accessibility and view of my frqs was a overall little harder to navigate and find the outputs: The person whose frqs I reviewed, Kira, used Replit to deploy her code and this made it much easier to follow through the progression of the frq when user input was asked. Instead of having to first input all the data and get one output at the end, like for my frqs, she was able to separate each step of the frq and give intermediate outputs as well.
- A strength in my frqs was how I included inputs for most of my frqs and had the default values listed made it easier to follow my code on the runtime. My crossover partner also found this helpful in establishing the context for my code.
- For Unit 3, my crossover partner just used default values to output the information about the party invitation and compare two of them while I took two different user inputs and compared them. I feel that this allowed my frq to be a little more thorough as I was able to compare two different objects as they were changing with different user inputs.
- For Unit 4, my crossover partner used a different approach in her code to find the starting index of the largest streak. She kept track of the starting index throughout her `for` loop while I simply found the starting index of the longest streak string after the `for` loop to find the largest streak was completed. By looking at her code as well, I was able to learn a different way to accomplish the same thing and gain a better understanding on how `if-else` statements can be used within `for` loops.
- For Unit 5, my crossover partner also included a part on her runtime where she gave information on the number of passwords given. She didn't have inputs for this part of her frq, so I could have implemented something similar to this and also expanded on it, by adding to the password count each time someone inputted information to get a password.

**Comment by 4disease** [comment]
| FRQ | Completed? | Deployed? | Documentation | Input | Extra Comments | Points |
|----|----|----|----|----|----|
| 2 | Yes | Yes | Yes | Yes | The layout of this FRQ is good overall but the way that each part of it has its own answer button + not all of them are answered at once is a bit confusing. Might be better if you input all numbers at once and only have one answer button. | 1.5/1.5 |
| 3 | Yes | Yes | Yes | Yes | Not many things to improve on for this FRQ, it is good overall, the only organizational improvement you could make is to clarify that the bolded text is the output | 1.5/1.5 |
| 4 | Yes | Yes | Yes | Yes | Again, the layout of the FRQ is good, but it may be helpful to have the user put all inputs in and hit the answer button once instead of having to reload the page twice to see the answer for both parts.  | 1/1 |
| 5 | Yes | Yes | Yes | Yes | The prompts for the invite are helpful in terms of what the user needs to input. Similarly to the above FRQs, it may be good to clarify that the bolded text is the output.  | 1/1 |
| 6 | Yes | Yes | Yes | Yes | The default values being provided are useful here. Also, the fact that you listed the equation for wages and 10% bonus is nice. It helps with putting your work in context with the actual FRQ.  | 1/1 |
| 7 | Yes | Yes | Yes | Yes |This FRQ is easy to view overall, I like how you gave the user the opportunity to build their own used username list. It may be good to clarify that Possible UserNames Set 2 is the set that results from eliminating Possible UserNames Set 1. Maybe a before and after of removing Possible UserNames Set 1? | 1/1 |
| 8 | Yes | Yes | Yes | Yes |The visualization of the crop field is useful to look at from a users perspective. I feel like the prompts for this FRQs are fairly straightforward. | 1/1 |
| 9 | Yes | Yes | Yes | Yes |Simple implementation of the FRQ that follows the collegeboard question. If you planned to implement input with this, you could give the option of inputting their own book/animal with its own unique attributes. | 1/1 |
| 10 | Yes | Yes | Yes | Yes |Good layout of FRQ and easy to use. Once again, I'd put a label on the output to indicate that it is the result of the user input. | 1/1 |
