### ISSUE TITLE
Sami CrossOver Grading

### ISSUE THREAD

**Issue by SamiDeshatty** [dsblack0/runtime-terror#81]

**Comment by SamiDeshatty** [comment]
SELF REVIEW: 

Jonathan's FRQs were essentially perfect. ALl working, all had input and output and ran without lag. 
I don't think mine were that good. While I met the requirements I am going to be working on having input and output for all 10 FRQs, and I will also work on making them easy to run since replit is quite slow and not very user friendly. 

While i do have to compare 3 FRQs to Jonathan's, I think mine are all at a level lower than his since there are still a couple of bugs to work out. In the last 3 FRQs. They work but not efficiently. 
On the other hand I think my learning summaries from each FRQ were significant.

**Comment by jlaaa** [comment]
1.
.8/.9 pts - FRQs under management - 9 FRQs are posted on replit [https://replit.com/@SamiDeshatty/College-Board-2021-AP-CSA-FRQs#PlotMain.java](), but some of them are not done and no page to talk about FRQ learnings.

.05/.1 - At least 2 FRQs contain input and output - 3 FRQs contain output, but none of the FRQs contain input that can be supplied by the user.

2.
Compare 3 FRQs
- For the Plot FRQ for Unit 8 Question 1, she has hardcoded input while I used usersupplied input. I think her idea for hardcoded input is better in this specific FRQ because entering the entire Plot is very cumbersome for the visitor and I should have at least had a test input that the user could choose to run instead of having to type out the 2D array of inputs.
- For the Light Sequence FRQ for Unit 2, I think my usage of user supplied input was better because this input was just a few numbers that can easily be supplied by the user. But I also could of had test inputs as well.
- For the LongestStreak FRQ, I used multiple `ArrayList` to loop through, but she used a for loop and string manipulation. I think her method was better because `ArrayList` is a dependency that can just be avoided and adds uncessary complexity to the program.

Summary Reflection
- Overall I think I did well on having user supplied input in the FRQ's, but I think I have some added complexity that i can reduce by using java's builtin functions that can be used, for example string manipuation methods.
